#!/bin/bash

source ~/.config/start-project/config || (echo "\nCan't find config file..\nQuitting.." && exit)


[ -z "$username" ] && echo 'Please specify your username on ~/.config/start-project/config' && exit 

[ -z "$githost" ] && echo ' Please specify correctly which git host are you using on ~/.config/start-project/config' && exit 

[ -z "$pat" ] && echo 'Cant find $projects please specify correctly on ~/.config/start-project/config' && exit 
[ ! -L $pat ] || ( echo "Cant find $projects please specify correctly on ~/.config/start-project/config" && exit )

[ -z "$projects" ] && echo 'Cant find $projects please specify correctly on ~/.config/start-project/config' && exit 
[ ! -L $projects ] || ( echo "Cant find $projects please specify correctly on ~/.config/start-project/config" && exit )

cd $projects &&
echo "Creating The Project : $1" &&
mkdir $1 &&
cd $1 &&
pwd &&
touch .gitignore &&
printf "githubApiLogs.txt\ngitlabApiLogs.txt" >> .gitignore &&
echo "Creating README.md" &&
touch README.md &&
echo "# $1" >> README.md &&
echo "Creating TODO.md" &&
touch TODO.md && printf "# TODO\n For **$1**\n---\n\n### Todo\n\n- [ ] Example Todo\n\n### In Progress..\n\n- [ ] Example Todo In Progress\n\t- [ ] Example Sub-Task\n\n### Done ✓\n\n- [x] Example Todo Done" >> TODO.md &&
if [[ $githost == "github" || $githost == "Github" || $githost == "GitHub" ]]
then
    echo "Creating Github Repository" &&
    curl -s -u "$username:$(cat $pat)" https://api.github.com/user/repos -d "{\"name\":\"$1\", \"private\":\"$private\"}" >> githubApiLogs.txt &&
    echo "https://github.com/$username/$1" 
fi &&
if [[ $githost == "gitlab" || $githost == "Gitlab" || $githost == "GitLab" ]]
then
    echo "Creating Gitlab Repository" &&
    curl -H "Content-Type:application/json" https://gitlab.com/api/v4/projects?private_token=$pat -d "{ \"name\": \"test\" , \"private\":\"$private\"}" >> gitlabApiLogs.txt &&
    echo "https://gitlab.com/$username/$1" 
fi &&
echo "Creating Git environment" &&
git init -q &&
echo "Syncing with project repo" &&
git remote add origin https://github.com/$username/$1.git &&
git add . &&
git commit -q -m "initial commit" &&
git push -q -u origin master &&
echo "Project Created!"
